[en]
title = "WinWisely.org - Help Scale Courage Now"
contentDir = "content/en"
languageName ="English"
languageCode= "en-us"
#if colon ":" must be prefixed with a space : "&nbsp;" (example in [fr])
beforeColon= ""
# Weight used for sorting. (alphabetical order using languageCode, with English first)
weight = 10
description = """
  WinWisely.org is a non-profit tech startup developing a mobile-friendly, open-source, one-stop, groundbreaking volunteer recruitment app.
"""


